import re


def ConvertTrigEditPlusTrigger(s):
    # UPRP
    '''
    CreateUnitWithProperties(1, "Zerg Lurker", "c11", P8, {
        burrowed = true,
    });
    '''
    s = re.sub(
        r"    CreateUnitWithProperties\((.*)\{\n([^}]*)\}\);",
        "    CreateUnitWithProperties(\\1UnitProperty(\n\\2));", s)

    # Trigger fields
    s = re.sub(r"^Trigger {", "Trigger(", s, flags=re.MULTILINE)
    s = re.sub(r"^    players = \{(.+)\},\n", "    players=[\\1],\n", s, flags=re.MULTILINE)
    s = re.sub(r"^    conditions = \{\n", "    conditions=[\n", s, flags=re.MULTILINE)
    s = re.sub(r"^    actions = \{\n", "    actions=[\n", s, flags=re.MULTILINE)
    s = re.sub(r"^    flags = {(.+)},\n", "    flags=[\\1],\n", s, flags=re.MULTILINE)
    s = re.sub(r"^    \},\n", "    ],\n", s, flags=re.MULTILINE)
    s = re.sub(r"^        (.+);\n", "        \\1,\n", s, flags=re.MULTILINE)
    s = re.sub(r"--(.+)", "#\\1", s)  # comments
    s = re.sub(r"\n*# This text is generated by TrigEditPlus\n*", '', s)
    s = re.sub(r"\n{3,}", "\n\n", s)
    s = re.sub(r"^\}\n", ")\n", s, flags=re.MULTILINE)

    # Some fixes
    s = s.replace("\"Any unit\"", "\"(any unit)\"")
    s = s.replace("\"Men\"", "\"(men)\"")
    s = s.replace("\"Buildings\"", "\"(buildings)\"")
    s = s.replace("\"Factories\"", "\"(factories)\"")

    s = s.replace("= true,\n", "= True,\n")
    s = s.replace("= false,\n", "= False,\n")

    return s
